### ISSUE TITLE
Backlight shortcut select + r not working on fc 3000 tft (V2 TFT: fc3000_tft2_od_jutleys_no_roms.img.7z (display model T2815_M110_24C_25)

### ISSUE THREAD

**Issue by Miguel-hrvs** [steward-fu/fc3000#1]

**Comment by steward-fu** [comment]
Sorry, due to some reasons, I have stopped maintaining this device some time ago.

**Comment by Miguel-hrvs** [comment]
No problem, thanks for the response. I made some scripts to change the brightness, the problem was with the jckl not the jutleys. With the jutleys image the brightness shortcuts works great. Thanks for this cfw. If I have some time, maybe I'll try to improve or update this firmware a little.
